version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - ./.env
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD